#!/usr/bin/env python
"""
   jj:    A simple command-line interface for managing
          multiple project to-do lists, creating note-histories
          for tasks done, and piecing together a daily task list
          from the "job jar" of todos still waiting to
          be completed.

          The system explicitly rejects the notion of due-dates,
          dependencies, sub-tasks etc., since these are already
          well covered by other tools.

   Flags: A task can have any combination of three status flags.
          Flags occur in any order at the start of the task label.
          * marks a task as started or in-progress
          ! marks a task as being picked for work today
          ~ marks a project or task as sleeping

          Sleeping projects and tasks are excluded from reports
          unless the -a option is present.

   ID values:
          Each job is given an id based on the MD5 hash of its text,
          so that log records and notes can be associated with it,
          but nobody has time to type in a 30-character string just to
          mark a job complete. So in practice, only the last 2 digits
          of the id string are shown. This is usually fine, but on 
          rare occasions, two jobs may have the same final digits. If
          this happens, just relist the jobs using the "-i" option to 
          increase the number of digits shown in the id values.

   Usage: 
      jj [options] stats
      jj [options] projects
      jj [options] add PROJ [JOBSTRING...]
      jj [options] (list|picked|today|sleeping|started) [PROJ]
      jj [options] (pick|unpick|start|finish) PROJ JOBID...
      jj [options] delete PROJ [JOBID]
      jj [options] mv PROJFROM PROJTO JOBID...
      jj [options] (report|did) DATE [PROJ]
      jj [options] log PROJ JOBID MESSAGE...
      jj [options] sleep PROJ [JOBID...]
      jj [options] search TERM...
      jj [options] wake PROJ [JOBID...]
      jj -h | --help
      jj -V | --version

   Options:
      -d      # Dump modified data file to STDOUT rather than writing to file
      -a      # Report ALL projects/tasks, including ~-sleeping ones
      -D PATH # Look in directory at PATH for .job.jj and .log.jj files
      -i N    # Show N digits of the job id (defuault = 2)
      -w DT   # Use DT instead of today in the logs for current operation
      -y      # Required extra confirmation for extreme commands like 'delete'
      -v      # Display verbose output
      -V      # Display version information

   Created 2018 by Jefferson Smith <jefferson@smithicus.com>
   Check out my tools, videos, and novels at http://creativityhacker.ca
"""

import os
import re
import hashlib
import datetime
from docopt import docopt


# process command line args
args = docopt(__doc__, version='jj version 0.0.1')
#print args

def mention(outstr):
    if args['-v']:
        print outstr

# by default, use the data files from the user's home directory
todo_file = os.path.expanduser("~/.jobs.jj")
log_file = os.path.expanduser("~/.log.jj")

# if they exist, use data files found in the current directory
if os.getcwd() != os.path.expanduser("~"):
    if os.path.exists(".jobs.jj"):
        todo_file = ".jobs.jj"
        print "Using job data file in current directory."
    if os.path.exists(".log.jj"):
        log_file = ".log.jj"

# if the user explicitly specifies an override, use the provided files
if '-D' in args and args['-D']:
   todo_file = os.path.join(args['-D'], '.jobs.jj')
   log_file = os.path.join(args['-D'], '.log.jj')

def getDateArg(instr):
    if re.match("\d\d\d\d-\d\d-\d\d", instr.strip()):
        return instr.strip()
    elif instr.lower() == 'today':
        dt = datetime.date.today()
        return dt.strftime("%Y-%m-%d")
    elif instr.lower() == 'yesterday':
        dt = datetime.date.today() - datetime.timedelta(1)
        return dt.strftime("%Y-%m-%d")
    return None

# determine what date should be shown in the log
if args['-w']:
    dstr =  getDateArg(args['-w'])
    if dstr:
        log_date = dstr
    else:
        print "Date provided in -w option must be in the form YYYY-MM-DD"
        exit()
else:
    log_date = datetime.datetime.now().strftime("%Y-%m-%d")
mention("Logging date: %s" % log_date)

idlen = 2
projects = []
datachanged = False

if args['-i']:
    idlen = int(args['-i'])

mention("Todo file: %s" % todo_file)
mention("Log file: %s" % log_file)

"""
Format of log file:
YYYY-MM-DD PROJ JOBID Message...
"""

def WriteLog(logfile, projtag, jobid, msg):
    with open(logfile, 'a') as fh:
        fh.write("%s %s %s %s\n" % (log_date, projtag, jobid, msg))


def breakline(line, width):
    head = ''
    tail = ''
    for i in range(width, 0, -1):
        if line[i] == ' ':
            head = line[:i]
            tail = line[i+1:]
            return head, tail
    head = "%s..." % line[:width-3]
    tail = ''
    return head, tail
    

def print_multi(linelist, columnwide, wrapindent=4):
    # first step, remake the list as width-limited single column
    newlines = []
    for l in linelist:
        if len(l) <= columnwide:
            newlines.append(l)
        else:
            head, tail = breakline(l, columnwide)
            newlines.append(head)
            while tail and len(tail) > columnwide-wrapindent:
                head, tail = breakline(tail, columnwide-wrapindent)
                newlines.append(" "*wrapindent + head)
            if len(tail):
                newlines.append(" "*wrapindent + tail)

    # second step, figure out where to break the column
    th, tw = os.popen('stty size', 'r').read().split()
    termwide = int(tw)
    cols = int((termwide/columnwide))
    gap = 0
    if cols == 1:
        columnwide = termwide
    else:
        gap = int( (termwide-(cols*columnwide))/(cols-1) )

    # see if we can find the headline nearest the half-way point.
    # Headlines are lines that begin in the first column.
    headlines = []
    for i in range(0, len(newlines)):
        if newlines[i] and newlines[i][0] != ' ':
            headlines.append(i)
    newcol = 0
    newcoldist = 10000
    midi = len(newlines)/2
    for i in headlines:
        dist = abs(i-midi)
        if dist < newcoldist:
            newcoldist = dist
            newcol = i
    # newcol is now the headline closest to the midpoint 
    # of all the lines to be printed

    # third step, start printing
    if newcol and cols > 1:
        i = 0
        j = newcol
        numlines = len(newlines)
        while i < newcol or j < numlines:
            left = ''
            if i < newcol:
                left = newlines[i]
            right = ''
            if j < numlines:
                right = newlines[j]
            l = left.ljust(columnwide) + ' '*gap + right
            print l
            i += 1
            j += 1
    else:
        for l in newlines:
            print l

def JobOrdering(a, b):
    """We want ~ jobs to display at the end, and all other flagged jobs
       to display at the top."""
    if '~' in a and '~' in b:
        return cmp(a,b)
    elif '~' in a:
        return 1
    elif '~' in b:
        return -1
    else:
        return -1*cmp(a,b)

class Job(object):
    def __init__(self, jobstr):
        doflags = True
        self.jobstr = ''
        self.flags = ''
        for c in jobstr:
            if doflags: 
                if c in "~*!":
                    self.flags += c
                else:
                    self.jobstr += c
                    doflags = False
            else:
                self.jobstr += c
        self.jobstr = self.jobstr.strip()
        self.flags = ''.join(sorted(self.flags, reverse=True)) # sort ~ to front
        self.id = hashlib.md5(self.jobstr).hexdigest()

    def getLine(self):
        if self.flags:
            return "%s %s" % (self.flags, self.jobstr)
        else:
            return "%s" % (self.jobstr)

    def getIDTag(self):
        return self.id[-idlen:]

    def isSleeping(self):
        return '~' in self.flags

    def isStarted(self):
        return '*' in self.flags

    def isPicked(self):
        return '!' in self.flags

    def isInScope(self):
        return args['-a'] or not self.isSleeping()

    def pick(self):
        if '!' not in self.flags:
            self.flags = ''.join(sorted(self.flags + '!', reverse=True))

    def unpick(self):
        if '!' in self.flags:
            self.flags = self.flags.replace('!', '')

    def sleep(self):
        if '~' not in self.flags:
            self.flags = ''.join(sorted(self.flags + '~', reverse=True))

    def wake(self):
        if '~' in self.flags:
            self.flags = self.flags.replace('~', '')

    def start(self):
        if '*' not in self.flags:
            self.flags = ''.join(sorted(self.flags + '*', reverse=True))


class Project(object):
    def __init__(self, projtag):
        self.jobs = []
        doflags = True
        self.projtag = ''
        self.flags = ''
        for c in projtag.strip():
            if doflags: 
                if c in "~":
                    self.flags += c
                else:
                    self.projtag += c
                    doflags = False
            else:
                self.projtag += c

    def isInScope(self):
        if args['PROJ']:
            selector = args['PROJ'].lower()
            mytag = self.projtag.lower()
            return mytag == selector
        else:
            return not self.isSleeping() or args['-a']

    def isSleeping(self):
        return '~' in self.flags

    def tagMatches(self, intag):
        projtag = self.projtag.lower()
        intag = intag.lower()
        return projtag == intag

    def addJob(self, jobstr):
        j = Job(jobstr) 
        self.jobs.append(j)
        return j

    def removeJob(self, j):
        if j in self.jobs:
            self.jobs.remove(j)
    
    def insertJob(self, j):
        self.jobs.append(j)

    def sleep(self):
        if '~' not in self.flags:
            self.flags += '~'

    def wake(self):
        if '~' in self.flags:
            self.flags = self.flags.replace('~', '')

    def getJobs(self):
        return sorted([j for j in self.jobs if j.isInScope()],
                        key=lambda x: x.flags, cmp=JobOrdering)

    def searchJobs(self, terms):
        # search for any term, case-insensitive
        hits = []
        for j in self.jobs:
            for term in terms:
                if term.lower() in j.jobstr.lower():
                    hits.append(j)
                    break
        return hits

    def getJobByID(self, id):
        hits = []
        for j in self.jobs:
            if j.id.lower().endswith(id.lower()):
                hits.append(j)
        if len(hits) == 1:
            return hits[0]
        elif len(hits) == 0:
            print "No job found matching id '%s' in project %s. Aborting." % (id, self.projtag)
            exit()
        else:
            print "Multiple jobs found matching id '%s'." % id
            print "List jobs again using higher -i value and try again."
            exit()

    def getStartedJobs(self):
        outs = []
        return [j for j in self.jobs if j.isStarted() and j.isInScope()]

    def getPickedJobs(self):
        outs = []
        return [j for j in self.jobs if j.isPicked() and j.isInScope()]

    def getSleepingJobs(self):
        outs = []
        return [j for j in self.jobs if j.isSleeping()]


def GetProjectByTag(intag):
    for p in projects:
        if p.tagMatches(intag):
            return p
    return None

# load all known projects and jobs
proj = None
with open(todo_file, 'r') as fh:
    for l in fh.readlines():
        line = l.strip()
        m = re.match('\[(\S+)\]', line)
        if m:
            proj = Project(m.group(1))
            projects.append(proj)
        elif len(line):
            proj.addJob(line)

if args['projects']:
    if args['-a']:
        print "All projects"
    else:
        print "Current projects"
    lines = []
    for p in projects:
        if p.isInScope():
            lines.append("%s%s" % (p.flags, p.projtag))
    # sort lines to put all sleepers together in the list
    slines = sorted(lines)
    print_multi(slines, columnwide=40, wrapindent = 0)

if args['list']:
    count = 0
    lines = []
    for p in projects:
        if p.isInScope():
            count += 1
            lines.append( "%s%s" % (p.flags, p.projtag))
            scopedJobs = p.getJobs()
            for j in scopedJobs:
                lines.append( "  (%s) %s" % (j.getIDTag(), j.getLine()))
            diff = len(p.jobs) - len(scopedJobs)
            if diff:
                lines.append("    ")
                lines.append("    %s +%d sleeping tasks" % (" "*idlen, diff))
            lines.append('')
    if not args['PROJ']: 
        # don't show sleeping proj count unless listing all projects
        diff = len(projects) - count
        if diff:
            lines.append( "+%d sleeping projects" % (diff) )
            lines.append('')
    print_multi(lines, columnwide=40, wrapindent = 5+idlen)

if args['search']:
    count = 0
    lines = []
    terms = args['TERM']
    for p in projects:
        if p.isInScope():
            count += 1
            scopedJobs = p.searchJobs(terms)
            if len(scopedJobs):
                lines.append( "%s%s" % (p.flags, p.projtag))
                for j in scopedJobs:
                    lines.append( "  (%s) %s" % (j.getIDTag(), j.getLine()))
                lines.append('')
    print_multi(lines, columnwide=40, wrapindent = 5+idlen)

if args['report']:
    dstr = getDateArg(args['DATE'])
    if dstr:
        target_date = dstr
    else:
        print "Report date must be in the form YYYY-MM-DD or the word 'yesterday'."
        exit()
    count = 0
    projlines = {}
    with open(log_file, 'r') as fh:
        for l in fh.readlines():
            line = l.strip()
            words = line.split()
            if words[0] == target_date:
                projtag = words[1]
                if not projtag in projlines:
                    projlines[projtag] = []
                projlines[projtag].append(' '.join(words[3:]))
    for projtag in projlines:
        print projtag
        for line in projlines[projtag]:
            print "   " + line
        print

if args['did']:
    dstr = getDateArg(args['DATE'])
    if dstr:
        target_date = dstr
    else:
        print "Report date must be in the form YYYY-MM-DD or the word 'yesterday'."
        exit()
    count = 0
    projlines = {}
    print "Jobs completed on %s" % dstr
    with open(log_file, 'r') as fh:
        for l in fh.readlines():
            line = l.strip()
            words = line.split()
            if words[0] == target_date and words[3] == "FINISHED":
                projtag = words[1]
                if not projtag in projlines:
                    projlines[projtag] = []
                if len(words) > 4:
                    jobstr = ' '.join(words[4:])
                    projlines[projtag].append(jobstr)
                else:
                    id = words[2][-2:]
                    projlines[projtag].append(id)
    if len(projlines):
        outlines = []
        for projtag in projlines:
            outlines.append(projtag)
            for jobstr in projlines[projtag]:
                chkmrk = u"\u2713"
                outlines.append( " " + chkmrk + " " + jobstr)
            outlines.append('   ')
        print_multi(outlines, columnwide=40, wrapindent = 3)
    else:
        print "None"

if args['started']:
    count = 0
    for p in projects:
        if p.isInScope():
            jjs = p.getStartedJobs()
            for j in jjs:
                print "%s: (%s) %s"% (p.projtag.rjust(10), j.getIDTag(), j.getLine())
                count += 1
    if not count:
        print "None".rjust(10)

if args['picked'] or args['today']:
    count = 0
    for p in projects:
        if p.isInScope():
            jjs = p.getPickedJobs()
            for j in jjs:
                print "%s: (%s) %s"% (p.projtag.rjust(10), j.getIDTag(),
                        j.getLine().replace('!','').strip())
                count += 1
    if not count:
        print "No jobs picked for today."

if args['sleeping']:
    count = 0
    lines = []
    lines.append( "Sleeping Tasks:" )
    for p in projects:
        if p.isInScope():
            jjs = p.getSleepingJobs()
            for j in jjs:
                lines.append( "%s: (%s) %s"% (p.projtag.rjust(10), j.getIDTag(), j.getLine()) )
                count += 1
    if not count:
        lines.append( "None".rjust(10) )
    lines.append('')
    lines.append( "Sleeping Projects:" )
    count = 0
    for p in projects:
        if p.isSleeping():
            lines.append( "%s"% p.projtag.rjust(10) )
            count += 1
    if not count:
        lines.append( "None".rjust(10) )
    print_multi(lines, columnwide=40, wrapindent = 10+5+idlen)

if args['stats']:
    jobcount = 0
    startedcount = 0
    sleepingcount = 0
    pickedcount = 0
    print "Projects: %d" % len(projects)
    print "Sleeping Projects: %d" % len([p for p in projects if p.isSleeping()])
    for p in projects:
        jobcount += len(p.jobs)
        for j in p.jobs:
            if j.isSleeping():
                sleepingcount += 1
            if j.isStarted():
                startedcount += 1
            if j.isPicked():
                pickedcount += 1
    print "Total Jobs: %d" % jobcount
    print "Started Jobs: %d" % startedcount
    print "Sleeping Jobs: %d" % sleepingcount
    print "Picked Jobs: %d" % pickedcount

if args['add']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        if len(args['JOBSTRING']) > 0:
            print "Project '%s' doesn't exist." % projtag
            print "Create the project before trying to add jobs to it."
            exit()
        p = Project(projtag)
        projects.append(p)
        datachanged = 1
        print "Project %s created."%projtag
        WriteLog(log_file, projtag, 0, "CREATED")
    if args['JOBSTRING']:
        jstr = ' '.join(args['JOBSTRING'])
        j = p.addJob(jstr)
        datachanged = 1
        print "Job #%s \"%s\" added to project %s."%(j.getIDTag(), j.getLine(), p.projtag)
        WriteLog(log_file, p.projtag, j.id, "CREATED: %s"%j.jobstr.strip())

if args['delete']:
    p = GetProjectByTag(args['PROJ'])
    if not p:
        print "No such project exists. Nothing to delete."
        exit()
    if len(args['JOBID']) > 1:
        print "Jobs can only be deleted one at a time."
        exit()
    if len(args['JOBID']) == 0:
        if len(p.jobs) == 0:
            projects.remove(p)
            datachanged = 1
            WriteLog(log_file, p.projtag, 0, "DELETED")
            print "Project %s deleted." % p.projtag
        else:
            print "Project %s has jobs. Only empty projects can be deleted." % p.projtag
    else:
        id = args['JOBID'][0]
        j = p.getJobByID(id)
        if not j:
            print "No such JOBID (%s) in that project. Nothing to delete." % id
            exit()
        if not args['-y']:
            print "Deletion cannot be undone, so confirmation is required."
            print "TARGETED JOB: %s" % j.getLine()
            print "If you really mean it, run the command again with the -y option."
            exit()
        p.removeJob(j)
        datachanged = 1
        WriteLog(log_file, p.projtag, j.id, "DELETED")
        print "Job \"%s\" deleted from project %s" % (j.getLine(), p.projtag)

if args['pick']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "No such project exists. Nothing to pick."
        exit()
    joblist = []
    for id in args['JOBID']:
        j = p.getJobByID(id)
        if not j:
            print "No job with id %s in that project." % id
            continue
        if j.isPicked():
            print "Job \"%s\" is already picked."%j.getLine()
            continue
        joblist.append(j)
    for j in joblist:
        j.pick()
        datachanged = 1
        WriteLog(log_file, p.projtag, j.id, "PICKED")
        print "Job \"%s\" from project %s picked" % (j.getLine(), p.projtag)

if args['unpick']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "No such project exists. Nothing to unpick."
        exit()
    joblist = []
    for id in args['JOBID']:
        j = p.getJobByID(id)
        if not j:
            print "No job with id %s in that project." % id
            continue
        if not j.isPicked():
            print "Job %s is not picked so it cannot be unpicked."%id
            continue
        joblist.append(j)
    for j in joblist:
        j.unpick()
        print "Job \"%s\" from project %s unpicked" % (j.getLine(), p.projtag)
        datachanged = 1
        WriteLog(log_file, p.projtag, j.id, "UNPICKED")

if args['mv']:
    projfromtag = args['PROJFROM']
    projtotag = args['PROJTO']
    pfrom = GetProjectByTag(projfromtag)
    if not pfrom:
        print "No such project (%s) exists. No project to move from." % projfromtag
        exit()
    pto = GetProjectByTag(projtotag)
    if not pto:
        print "No such project (%s) exists. No project to move to." % projtotag
        exit()
    joblist = []
    for id in args['JOBID']:
        j = pfrom.getJobByID(id)
        if not j:
            print "No job with id %s in project %s. Aborting." % (id, projfromtag)
            exit()
        joblist.append(j)
    for j in joblist:
        pfrom.removeJob(j)
        pto.insertJob(j)
        print "Job \"%s\" moved from project %s to project %s" % (j.getLine(), pfrom.projtag, pto.projtag)
        datachanged = 1
        WriteLog(log_file, pfrom.projtag, j.id, "MOVEDTO %s"%pto.projtag)
        WriteLog(log_file, pto.projtag, j.id, "MOVEDFROM %s"%pfrom.projtag)

if args['sleep']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "No such project exists. Nothing put to sleep."
        exit()
    joblist = []
    for id in args['JOBID']:
        j = p.getJobByID(id)
        if not j:
            print "No job with id %s in that project." % id
            continue
        if j.isSleeping():
            print "Job \"%s\" is already asleep."%j.getLine()
            continue
        joblist.append(j)
    if len(joblist):
        for j in joblist:
            j.sleep()
            datachanged = 1
            WriteLog(log_file, p.projtag, j.id, "SLEEP")
            print "Job \"%s\" from project %s now sleeping" % (j.getLine(), p.projtag)
    else:
        if p.isSleeping():
            print "Project \"%s\" is already asleep."%p.projtag
            exit()
        else:
            p.sleep()
            datachanged = 1
            WriteLog(log_file, p.projtag, 0, "SLEEP")
            print "Project %s now sleeping" % (p.projtag)

if args['wake']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "No such project exists. Nothing to wake."
        exit()
    joblist = []
    for id in args['JOBID']:
        j = p.getJobByID(id)
        if not j:
            print "No job with id %s in that project." % id
            continue
        if not j.isSleeping():
            print "Job \"%s\" is already awake."%j.getLine()
            continue
        joblist.append(j)
    if len(joblist):
        for j in joblist:
            j.wake()
            datachanged = 1
            WriteLog(log_file, p.projtag, j.id, "WAKE")
            print "Job \"%s\" from project %s now awake" % (j.getLine(), p.projtag)
    else:
        if not p.isSleeping():
            print "Project \"%s\" is already awake."%p.projtag
            exit()
        else:
            p.wake()
            datachanged = 1
            WriteLog(log_file, p.projtag, 0, "WAKE")
            print "Project %s now awake" % (p.projtag)

if args['start']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "No such project exists. Nothing to start."
        exit()
    joblist = []
    for id in args['JOBID']:
        j = p.getJobByID(id)
        if not j:
            print "No job with id %s in that project." % id
            continue
        if j.isStarted():
            print "Job %s is already started."%id
            continue
        joblist.append(j)
    for j in joblist:
        j.start()
        datachanged = 1
        print "Job \"%s\" from project %s started" % (j.getLine(), p.projtag)
        WriteLog(log_file, p.projtag, j.id, "STARTED")

if args['finish']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "No such project exists. Nothing to finish."
        exit()
    joblist = []
    for id in args['JOBID']:
        j = p.getJobByID(id)
        if not j:
            print "No job with id %s in that project." % id
            continue
        if not j.isStarted():
            mention("That job wasn't started. Marking it started and finished.")
            WriteLog(log_file, p.projtag, j.id, "STARTED")
        joblist.append(j)
    for j in joblist:
        p.removeJob(j)
        datachanged = 1
        print("Job \"%s\" from project %s logged as finished." % (j.getLine(), projtag))
        WriteLog(log_file, p.projtag, j.id, "FINISHED %s"%j.jobstr)

if args['log']:
    projtag = args['PROJ']
    p = GetProjectByTag(projtag)
    if not p:
        print "Looks like you forgot to specify the PROJ tag."
        print "No log entry added."
        exit()
    if len(args['JOBID']) == 0:
        print "No job id given, so there's nowhere to put the log entry."
        exit()
    id = args['JOBID'][0]
    j = p.getJobByID(id)
    if not j:
        print "No job found with that id. No log entry made."
        exit()
    if len(args['MESSAGE']) == 0:
        print "No message provided to enter into log."
        exit()
    logstr = ' '.join(args['MESSAGE'])
    WriteLog(log_file, p.projtag, j.id, "LOG: %s" % logstr)
    datachanged = 0  # log entries do not modify the job file
    print "Note logged to job %s \"%s\"." % (p.projtag, j.getLine())

# This should be the last thing
if args['-d']:
    for p in projects:
        print "[%s%s]" % (p.flags, p.projtag)
        for j in p.jobs:
            print j.getLine()
        print
elif datachanged:
    with open(todo_file, 'w') as fh:
        for p in projects:
            fh.write("[%s%s]\n" % (p.flags, p.projtag))
            for j in p.jobs:
                fh.write("%s\n" % j.getLine())
            fh.write("\n")
    mention("Database updated.")
else:
    mention("Database unchanged.")
